
# gloabl vars
ci_cd_namespace: &ci_cd "labs-ci-cd"
pm_namespace: &pm "labs-pm"
ops_namespace: &ops "labs-cluster-ops"
dev_namespace: &dev "labs-dev"
test_namespace: &test "labs-test"
staging_namespace: &stage "labs-staging"

# App of applications list
applications:

  # Nexus
  - name: nexus
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_ref: "1.1.4"
    destination: cansu-tooling
    values:
      service:
        name: nexus


  # Sonarqube
  - name: sonarqube
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonarqube
    source_ref: "0.1.0"
    destination: cansu-testing
    values:
      # if integrating into an existing sealed secret or other cluster secret 
      # account:
      #   existingSecret: sonarqube-auth
      initContainers: true
      plugins:
        install:
          - https://github.com/checkstyle/sonar-checkstyle/releases/download/8.40/checkstyle-sonar-plugin-8.40.jar
          - https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar
