release: "pm"

applications:
  # Owncloud
  - name: owncloud
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/owncloud
    source_ref: "owncloud-0.0.14"
    values:
      route:
        enabled: true
      hostname: owncloud.apps.hivec.sandbox1559.opentlc.com
    ignore_differences:
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
          - /spec/template/spec/containers/0/image
          - /spec/triggers/0/imageChangeParams/lastTriggeredImage
